### ISSUE TITLE
Question about PPO Implementation

### ISSUE THREAD

**Issue by boscotsang** [Hwhitetooth/lirpg#3]
In PPO2 implementation, it seems that there is no implementation on equation (7) - (10) which calculate the deriviate of param \ita. Did I missed something? Thanks.

**Comment by Hwhitetooth** [comment]
Hi @boscotsang,

Please see [here](https://github.com/Hwhitetooth/lirpg/issues/2#issuecomment-678381696) for clarification.

Best regards,
Zeyu
